name: Swift

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run:  xcodebuild -scheme Superstring-Package test -destination "name=iPhone 8"
